assets/styles/pages/inventario.less, views/pages/inventario.ejs
=> Revert "Actualizando Inventario"

assets/styles/bootstrap-overrides.less, assets/styles/styleguide/colors.less
- Se agregaron las variables de los colores a como la empresa **IMAGO** especifico.
- Se sambio el color de los botones por las variables creadas
=> Cambiando los colores de los botones

assets/js/pages/ventas/cotizaciones.page.js, package.json, views/pages/ventas/cotizaciones.ejs
Se agrego un nuevo filtro para las cotizaciones
Se termino el modal para mostrar mas informacion.
se actualizo el package.json para agregar autoers y git url
=> Agregando funcionalidad a pagina cotizacion

api/models/Inventario/Articulos.js, assets/js/pages/ventas/cotizaciones.page.js, config/datastores.js, package-lock.json, package.json, views/pages/ventas/cotizaciones.ejs
- Agregando modelo **Inventario**
- Agregando el adaptador de **MongoDB**
=> Agregando modelo y cambiando configuración 

assets/js/pages/inventario.page.js, views/pages/inventario.ejs
=> Revert "Buscar"

views/pages/inventario.ejs, views/pages/ventas/cotizaciones.ejs, views/pages/ventas/ventas.ejs
Se le agrego un formato igualitario a todos los modales
=> Heuristicas

api/controllers/ventas/view-ventas.js, assets/js/pages/ventas/ventas.page.js, views/pages/ventas/ventas.ejs
Cambios de el modal ver de la pagina ventas
=> Pagina ventas

views/pages/usuarios.ejs
Cambios de la vista de la pagina usuarios segun lo observado
=> Cambios de la vista

assets/js/pages/usuarios.page.js, views/pages/usuarios.ejs
Se cambiaron el tamaño y posición de los diseños de los botones respecto a la vista de "Inventario".
Se realizo la funcionalidad de la búsqueda respecto al nombre del usuario y el correo.
Se introdujo un mensaje en el caso de no encontrar al usuario.
=> Funcionalidad del buscador

assets/js/pages/usuarios.page.js, views/pages/inventario.ejs, views/pages/usuarios.ejs
Insercion del modal ayuda en el momento de la busqueda.
camnios en el boton de editar y a la hora de mostrar el modal de editar.
=> Modal ayuda

assets/js/pages/ventas/ventas.page.js, config/policies.js, views/pages/ventas/ventas.ejs
=> Revert "Dev"

views/pages/ventas/ventas.ejs
Se realizó el modal correspondiente al boton de ver en la tabla de filtro de busqueda de articulos en la ventana de ventas
=> Modal Ver y botón de filtro

views/layouts/layout.ejs
=> Removiendo las tabs no deseadas

api/models/Cliente/Clientes.js, api/models/Cliente/Contactos.js
Se crea version 1 de los modelos para almacenar los clientes y los contactos de cada cliente
=> Creacion de los modelos Cliente y Contacto (v. 1)

api/controllers/clientes/actualizar-cliente.js, api/controllers/clientes/eliminar-cliente.js, api/controllers/clientes/extraer-cliente.js, api/controllers/clientes/insertar-cliente.js, api/controllers/contactos/actualizar-contacto.js, api/controllers/contactos/eliminar-contacto.js, api/controllers/contactos/insertar-contacto.js, api/models/Cliente/Clientes.js, api/models/Cliente/Contactos.js, config/routes.js
-Validaciones de llaves únicas.
-Nuevo atributo Activo para los modelos Clientes y Contacto.
-Cambio de métodos de eliminar de cliente y contacto
=> Cambios en modelo de Cliente y Contacto

api/controllers/clientes/extraer-cliente.js, api/controllers/ventas/extraer-cotizacion.js, api/controllers/ventas/insertar-cotizacion.js
- Validacion a la hora de ingresar inventario
- Creacion metodo para buscar una cotizacion en base al ID
=> Cambios de backend

api/controllers/clientes/actualizar-cliente.js, api/controllers/clientes/insertar-cliente.js, api/models/Cliente/Clientes.js
Se agrega el atributo de "nombreReal" al modelo de cliente
=> Modificación del Modelo Cliente

api/controllers/contactos/actualizar-contacto.js, api/controllers/ventas/actualizar-cotizacion.js, config/routes.js
Cambio en validación en actualizar contacto.
Creación del método de actualizar cotización.
Ruta para el método de actualizar contacto.
=> Actualizar Cotización

api/controllers/ventas/eliminar-cotizacion.js, config/routes.js
Se creo el archivo con el método.
Se creo la ruta para el método eliminar-cotización
=> Creación Método Eliminar Cotización

api/models/Ventas/Cotizaciones.js
Agregando estado y cambiando articulos por jsonArticulos
=> Cambios en modelo Cotzaciones (v2)

api/controllers/ventas/actualizar-cotizacion.js
Se incluye el atributo de estado en el metodo de actualizar cotización para identificar el estado de la cotización dentro de la empresa por medio de actualiaciones
=> Atributo estado en actualizar-cotización

api/controllers/ventas/extraer-cotizacion.js, config/routes.js
-Se elimino el input de encargado.
-Se le dio formato a las rutas para los métodos de los APIs
=> Cambios en los inputs del Metodo de extraer cliente

api/controllers/ventas/actualizar-cotizacion.js
Se implemento del metodo de la verificacion del id del articulo y los precios en la base de datos
=> Modificación de Actualizar-Cotización

api/controllers/ventas/actualizar-cotizacion.js
Se incluye el atributo del id para realizar la búsqueda de la cotización mediante la introducción de los parámetros dentro de un mismo json
=> Nuevo atributo en Actualizar-Cotización

views/pages/ventas/ventas.ejs
se arreglo el buscador de la pagina de ventas, solo estaba lanzando dos articulos ahora manda todos los que sean necesarios
=> arreglo de busqueda en ventas

api/controllers/ventas/actualizar-cotizacion.js, api/controllers/ventas/copiar-cotizacion.js, config/routes.js
-Se crea el método de copiar cotización.
-Optimización de actualizar-cotización.
-Nueva ruta para copiar-cotización.
=> Método Copiar Cotización

api/controllers/ventas/actualizar-cotizacion.js, api/controllers/ventas/insertar-cotizacion.js, api/models/Ventas/Cotizaciones.js
Métodos Actualizados:
-Insertar Cotización.
-Actualizar Cotización.
=> Propiedad Comentario en Modelo Cotizaciones

config/routes.js
Se escribe la ruta de la mejor manera para el método de reservar una cotizacion y que no hayan conflictos en las pruebas
=> Actualización de las Rutas

package-lock.json, package.json
**Require**
```bash
npm install
```
=> Agregando librerias para reporte (CSV, XSLX)

api/controllers/clientes/insertar-cliente.js, api/controllers/contactos/insertar-contacto.js, api/controllers/entrance/login.js, api/controllers/ventas/view-cotizaciones.js, api/controllers/view-inventario.js, api/models/User.js, api/responses/idRepetido.js, assets/js/pages/inventario.page.js, assets/js/pages/ventas/actualizarCotizacion.page.js, assets/js/pages/ventas/ventas.page.js, package-lock.json, package.json
Se retocaron algunos archivos JS para correcciones de logica
=> Correcciones de codifo JS
